apiVersion: v1
kind: Service
metadata:
  name: jiaozifs-com-service
  labels:
    apptype: jiaozifs-com
spec:
  type: ClusterIP
  selector:
    app: jiaozifs-com
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80